# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasks.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btasks.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9a\x01\n\x0bNoteRequest\x12&\n\x05\x61ttrs\x18\x01 \x03(\x0b\x32\x17.NoteRequest.AttrsEntry\x12\x35\n\x10parent_container\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x85\x01\n\tNoteReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x05\x61ttrs\x18\x02 \x03(\x0b\x32\x15.NoteReply.AttrsEntry\x12\x18\n\x10parent_container\x18\x03 \x01(\x05\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"|\n\x10\x43ontainerRequest\x12+\n\x05\x61ttrs\x18\x01 \x03(\x0b\x32\x1c.ContainerRequest.AttrsEntry\x12\r\n\x05notes\x18\x02 \x03(\x05\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x84\x01\n\x0e\x43ontainerReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12)\n\x05\x61ttrs\x18\x02 \x03(\x0b\x32\x1a.ContainerReply.AttrsEntry\x12\r\n\x05notes\x18\x03 \x03(\x05\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"R\n\nConnection\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x65ndpoint_one\x18\x02 \x01(\x03\x12\x14\n\x0c\x65ndpoint_two\x18\x03 \x01(\x03\x12\x0c\n\x04text\x18\x04 \x01(\t\"-\n\x08\x44ocument\x12\r\n\x05notes\x18\x01 \x03(\x05\x12\x12\n\ncontainers\x18\x02 \x03(\x05\x32\x37\n\x0bNoteManager\x12(\n\nCreateNote\x12\x0c.NoteRequest\x1a\n.NoteReply\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_NOTEREQUEST_ATTRSENTRY = _descriptor.Descriptor(
  name='AttrsEntry',
  full_name='NoteRequest.AttrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='NoteRequest.AttrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='NoteRequest.AttrsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=202,
)

_NOTEREQUEST = _descriptor.Descriptor(
  name='NoteRequest',
  full_name='NoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attrs', full_name='NoteRequest.attrs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_container', full_name='NoteRequest.parent_container', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NOTEREQUEST_ATTRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=202,
)


_NOTEREPLY_ATTRSENTRY = _descriptor.Descriptor(
  name='AttrsEntry',
  full_name='NoteReply.AttrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='NoteReply.AttrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='NoteReply.AttrsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=202,
)

_NOTEREPLY = _descriptor.Descriptor(
  name='NoteReply',
  full_name='NoteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NoteReply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attrs', full_name='NoteReply.attrs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_container', full_name='NoteReply.parent_container', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NOTEREPLY_ATTRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=338,
)


_CONTAINERREQUEST_ATTRSENTRY = _descriptor.Descriptor(
  name='AttrsEntry',
  full_name='ContainerRequest.AttrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ContainerRequest.AttrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ContainerRequest.AttrsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=202,
)

_CONTAINERREQUEST = _descriptor.Descriptor(
  name='ContainerRequest',
  full_name='ContainerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attrs', full_name='ContainerRequest.attrs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='ContainerRequest.notes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONTAINERREQUEST_ATTRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=464,
)


_CONTAINERREPLY_ATTRSENTRY = _descriptor.Descriptor(
  name='AttrsEntry',
  full_name='ContainerReply.AttrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ContainerReply.AttrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ContainerReply.AttrsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=202,
)

_CONTAINERREPLY = _descriptor.Descriptor(
  name='ContainerReply',
  full_name='ContainerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ContainerReply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attrs', full_name='ContainerReply.attrs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='ContainerReply.notes', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONTAINERREPLY_ATTRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=599,
)


_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Connection.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endpoint_one', full_name='Connection.endpoint_one', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endpoint_two', full_name='Connection.endpoint_two', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='Connection.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=683,
)


_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notes', full_name='Document.notes', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='containers', full_name='Document.containers', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=730,
)

_NOTEREQUEST_ATTRSENTRY.containing_type = _NOTEREQUEST
_NOTEREQUEST.fields_by_name['attrs'].message_type = _NOTEREQUEST_ATTRSENTRY
_NOTEREQUEST.fields_by_name['parent_container'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_NOTEREPLY_ATTRSENTRY.containing_type = _NOTEREPLY
_NOTEREPLY.fields_by_name['attrs'].message_type = _NOTEREPLY_ATTRSENTRY
_CONTAINERREQUEST_ATTRSENTRY.containing_type = _CONTAINERREQUEST
_CONTAINERREQUEST.fields_by_name['attrs'].message_type = _CONTAINERREQUEST_ATTRSENTRY
_CONTAINERREPLY_ATTRSENTRY.containing_type = _CONTAINERREPLY
_CONTAINERREPLY.fields_by_name['attrs'].message_type = _CONTAINERREPLY_ATTRSENTRY
DESCRIPTOR.message_types_by_name['NoteRequest'] = _NOTEREQUEST
DESCRIPTOR.message_types_by_name['NoteReply'] = _NOTEREPLY
DESCRIPTOR.message_types_by_name['ContainerRequest'] = _CONTAINERREQUEST
DESCRIPTOR.message_types_by_name['ContainerReply'] = _CONTAINERREPLY
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NoteRequest = _reflection.GeneratedProtocolMessageType('NoteRequest', (_message.Message,), {

  'AttrsEntry' : _reflection.GeneratedProtocolMessageType('AttrsEntry', (_message.Message,), {
    'DESCRIPTOR' : _NOTEREQUEST_ATTRSENTRY,
    '__module__' : 'tasks_pb2'
    # @@protoc_insertion_point(class_scope:NoteRequest.AttrsEntry)
    })
  ,
  'DESCRIPTOR' : _NOTEREQUEST,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:NoteRequest)
  })
_sym_db.RegisterMessage(NoteRequest)
_sym_db.RegisterMessage(NoteRequest.AttrsEntry)

NoteReply = _reflection.GeneratedProtocolMessageType('NoteReply', (_message.Message,), {

  'AttrsEntry' : _reflection.GeneratedProtocolMessageType('AttrsEntry', (_message.Message,), {
    'DESCRIPTOR' : _NOTEREPLY_ATTRSENTRY,
    '__module__' : 'tasks_pb2'
    # @@protoc_insertion_point(class_scope:NoteReply.AttrsEntry)
    })
  ,
  'DESCRIPTOR' : _NOTEREPLY,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:NoteReply)
  })
_sym_db.RegisterMessage(NoteReply)
_sym_db.RegisterMessage(NoteReply.AttrsEntry)

ContainerRequest = _reflection.GeneratedProtocolMessageType('ContainerRequest', (_message.Message,), {

  'AttrsEntry' : _reflection.GeneratedProtocolMessageType('AttrsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONTAINERREQUEST_ATTRSENTRY,
    '__module__' : 'tasks_pb2'
    # @@protoc_insertion_point(class_scope:ContainerRequest.AttrsEntry)
    })
  ,
  'DESCRIPTOR' : _CONTAINERREQUEST,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:ContainerRequest)
  })
_sym_db.RegisterMessage(ContainerRequest)
_sym_db.RegisterMessage(ContainerRequest.AttrsEntry)

ContainerReply = _reflection.GeneratedProtocolMessageType('ContainerReply', (_message.Message,), {

  'AttrsEntry' : _reflection.GeneratedProtocolMessageType('AttrsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONTAINERREPLY_ATTRSENTRY,
    '__module__' : 'tasks_pb2'
    # @@protoc_insertion_point(class_scope:ContainerReply.AttrsEntry)
    })
  ,
  'DESCRIPTOR' : _CONTAINERREPLY,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:ContainerReply)
  })
_sym_db.RegisterMessage(ContainerReply)
_sym_db.RegisterMessage(ContainerReply.AttrsEntry)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTION,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:Connection)
  })
_sym_db.RegisterMessage(Connection)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENT,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:Document)
  })
_sym_db.RegisterMessage(Document)


_NOTEREQUEST_ATTRSENTRY._options = None
_NOTEREPLY_ATTRSENTRY._options = None
_CONTAINERREQUEST_ATTRSENTRY._options = None
_CONTAINERREPLY_ATTRSENTRY._options = None

_NOTEMANAGER = _descriptor.ServiceDescriptor(
  name='NoteManager',
  full_name='NoteManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=732,
  serialized_end=787,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateNote',
    full_name='NoteManager.CreateNote',
    index=0,
    containing_service=None,
    input_type=_NOTEREQUEST,
    output_type=_NOTEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOTEMANAGER)

DESCRIPTOR.services_by_name['NoteManager'] = _NOTEMANAGER

# @@protoc_insertion_point(module_scope)
