# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tasks_pb2 as tasks__pb2


class NoteManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateNote = channel.unary_unary(
        '/NoteManager/CreateNote',
        request_serializer=tasks__pb2.NoteRequest.SerializeToString,
        response_deserializer=tasks__pb2.NoteReply.FromString,
        )


class NoteManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateNote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NoteManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateNote': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNote,
          request_deserializer=tasks__pb2.NoteRequest.FromString,
          response_serializer=tasks__pb2.NoteReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NoteManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
